#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall polybar
polybar &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width          2
bspc config window_gap            8
bspc config top_padding           38
bspc config split_ratio           0.5
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled
bspc rule -a Nm-connection-editor state=floating
