#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall polybar
MONITOR=eDP-1 polybar default&
MONITOR=HDMI-2 polybar external&

bspc wm --reorder-monitors eDP-1 HDMI-2
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-2 -d EXTERNAL

bspc config border_width          2
bspc config window_gap            8
bspc config top_padding           38
bspc config split_ratio           0.5
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled
